### ISSUE TITLE
3 rare things that I don't know the reason

### ISSUE THREAD

**Issue by frangeris** [mustangostang/spyc#39]
Hi devs, 

**1)** Im trying to create a yml doc with some array, the doc get created but inside the doc there is `---` at the begin of the file, what is this?

``` php
$acceptance = [
    'class_name' => 'AcceptanceTester',
];
```

```
string(...) "--- <------- WHAT IS THIS?
class_name: AcceptanceTester
"
```

**2)** I would like to create something like this:

``` yml
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser
        - WebHelper
```

This is my code:

``` php
$enabled = "- PhpBrowser \n- WebHelper";
$acceptance = [
    'class_name' => 'AcceptanceTester',
    'modules' => [
        'enabled' => $enabled,
    ]
];
```

But instead I get:

``` yml

---
class_name: AcceptanceTester
modules:
    enabled: | <------------ WHY IS THIS HERE?
        - PhpBrowser 
        - WebHelper
```

**With a pipe( | ) and the previous `---` that I previously explained**

**3)** Im trying to create a field with this format:

``` yml
 url: 'http://someurl.com'
```

This is the code:

``` php
$module = [
    'modules' => [
        'config' => [
            'PhpBrowser' => [
                'url1' => $domain,
                'url2' => "'$domain'",
                'url3' => "$domain",
                'url4' => '\'$domain\''
            ]
        ]
    ]
];

```

And I get:

``` yml
modules:
    config:
        PhpBrowser:
            url1: http://someurl.com
            url2: "'http://someurl.com'"
            url3: http://someurl.com
            url4: "'$domain'"
```

Any solution, Thank you very much in advance!
