### ISSUE TITLE
YAMLDump: Strings don't get quoted properly

### ISSUE THREAD

**Issue by lukasbestle** [mustangostang/spyc#53]
**Test case:**

```php
$data = [
	[
		'name' => 'Lorem ipsum',
		'quote' => 'Dolor sit amet.'
	],
	[
		'name' => 'Consetetur sadipscing',
		'quote' => '"Elitr sed diam nonumy eirmod."'
	]
];

echo Spyc::YAMLDump($data);
```

**Expected behavior:**

The second entry is quoted by Spyc so that the quotes around the string get preserved:

```yaml
- 
  name: Lorem ipsum
  quote: Dolor sit amet.
- 
  name: Consetetur sadipscing
  quote: '"Elitr sed diam nonumy eirmod."'
```

**Actual behavior:**

The string is used as-is without quoting:

```yaml
- 
  name: Lorem ipsum
  quote: Dolor sit amet.
- 
  name: Consetetur sadipscing
  quote: "Elitr sed diam nonumy eirmod."
```

When parsing that YAML string again, the quotes are removed.
