### ISSUE TITLE
Replaces "n" with bool(false) but not "y" with bool(true)

### ISSUE THREAD

**Issue by demonking** [mustangostang/spyc#78]
```
    name: canaccess
    field: can_access
    convert:
        translate:
            -
                pattern: j
                replacement: 1
            -
                pattern: n
                replacement: 0
```

```
Result : 

 ["convert"]=>
    array(1) {
      ["translate"]=>
      array(2) {
        [0]=>
        array(2) {
          ["pattern"]=>
          string(1) "j"
          ["replacement"]=>
          int(1)
        }
        [1]=>
        array(2) {
          ["pattern"]=>
          bool(false)
          ["replacement"]=>
          int(0)
        }
      }

```
