### ISSUE TITLE
Error loading normal parent: child records

### ISSUE THREAD

**Issue by ppazos** [mustangostang/spyc#83]
This:

```
martin:
    name: Martin D'vloper
    job: Developer
    skill: Elite
```

Gives " Illegal string offset" error for the "name"
