### ISSUE TITLE
Support for compact inline notation

### ISSUE THREAD

**Issue by swt83** [mustangostang/spyc#9]
I've never used YAML before, and I am not familiar w/ the spec rules, but I need it for a certain project.  In this project, I'm finding that SPYC doesn't parse multidimensional arrays properly in every case, but oddly if I add a space before every "-" character in the file it will parse correctly.  Here is some sample YAML that I'm using as a test:

Does not work:

```
- alpha:
    foo: bar
    bar:
    - foo
  beta:
    foo: bar
    bar: foo
  charlie:
    foo: bar
    bar: foo
  delta:
  - foo: bar
    bar: foo
  - foo: bar
    bar: foo
```

Works:

```
 - alpha:
    foo: bar
    bar:
     - foo
  beta:
    foo: bar
    bar: foo
  charlie:
    foo: bar
    bar: foo
  delta:
   - foo: bar
    bar: foo
   - foo: bar
    bar: foo
```

Maybe the file I'm using as my source is formatted incorrectly.  Maybe there is a param in the class that I am missing that covers this.
